### ISSUE TITLE
Unable to determine linked PHP

### ISSUE THREAD

**Issue by jasperf** [aaemnnosttv/wp-cli-valet-command#30]
Upgraded Brew PHP to PHP 7.2 and linked new version as well as removed old one. When I check PHP version from command line it is 7.2 But when I try to create a new WordPress website it states it cannot determine the linked PHP version... Did a `brew unlink php && brew link php` too but it still gives me the same error. Restarting the terminal did not help either

````
Fatal error: Uncaught RuntimeException: 
                                   
  [DomainException]                
  Unable to determine linked PHP.  
                                   

secure [<domain>]

 in /Users/jasper/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-valet-command/src/Process/ShellCommand.php:65
Stack trace:
#0 /Users/jasper/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-valet-command/src/Process/SystemValet.php(28): WP_CLI_Valet\Process\ShellCommand->run('secure', ' 'gda'')
#1 [internal function]: WP_CLI_Valet\Process\SystemValet->secure('gda')
#2 /Users/jasper/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-valet-command/src/Facade.php(37): call_user_func_array(Array, Array)
#3 /Users/jasper/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-valet-command/src/ValetCommand.php(173): WP_CLI_Valet\Facade::__callStatic('secure', Array)
#4 [internal function]: WP_CLI_Valet\ValetCommand->_new(Array, Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#6 [internal  in /Users/jasper/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-valet-command/src/Process/ShellCommand.php on line 65
````

When I did 
```
brew link php72
Warning: Already linked: /usr/local/Cellar/php/7.2.2_14
To relink: brew unlink php && brew link php
````
and a relink:
````
brew unlink php && brew link php
Unlinking /usr/local/Cellar/php/7.2.2_14... 25 symlinks removed
Linking /usr/local/Cellar/php/7.2.2_14... 25 symlinks created
````
I still had the error
````
Fatal error: Uncaught RuntimeException: 
In Brew.php line 187:
                                   
  Unable to determine linked PHP.  
                                   

secure [<domain>]

 in /Users/jasper/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-valet-command/src/Process/ShellCommand.php:65
Stack trace:
#0 /Users/jasper/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-valet-command/src/Process/SystemValet.php(28): WP_CLI_Valet\Process\ShellCommand->run('secure', ' 'gda'')
#1 [internal function]: WP_CLI_Valet\Process\SystemValet->secure('gda')
#2 /Users/jasper/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-valet-command/src/Facade.php(37): call_user_func_array(Array, Array)
#3 /Users/jasper/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-valet-command/src/ValetCommand.php(173): WP_CLI_Valet\Facade::__callStatic('secure', Array)
#4 [internal function]: WP_CLI_Valet\ValetCommand->_new(Array, Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#6 [internal function]: WP_ in /Users/jasper/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-valet-command/src/Process/ShellCommand.php on line 65
````

**Comment by jasperf** [comment]
Never mind. Valet needed 7.1 in the end and would not work with 7.2 So after reinstalling all I was told so.

**Comment by aaemnnosttv** [comment]
Both valet and the wp-cli-valet command support php 7.2. This has to do with a recent change to how Homebrew names the linked php version in 7.2.

See https://github.com/laravel/valet/issues/528.

**Comment by jasperf** [comment]
@aaemnnosttv aha. Will check this out. Thanks a lot!
